server.port=8084
spring.application.name=pharmacy-service
spring.data.mongodb.uri=mongodb+srv://sudeepasandabhanu_db_user:wzAaQA0PbuBuDjtI@cluster0.gzbeg4i.mongodb.net/
spring.data.mongodb.database=pharmacydb
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
