server.port=8083
spring.application.name=appointment-service
spring.data.mongodb.uri=mongodb+srv://sudeepasandabhanu_db_user:wzAaQA0PbuBuDjtI@cluster0.gzbeg4i.mongodb.net/
spring.data.mongodb.database=appointmentdb
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
